theme: jekyll-theme-minimal
baseurl: "/cb2030"
remote_theme: pages-themes/dinky@v0.2.0
title: "CB2030"
description: "Here we store material for the Data Analysis part of the CB2030, Systems Biology course."
logo: assets/image/kth_logo.png

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-jupyter-notebook
relative_links:
  enabled: true
  collections: true
