name: cb2030
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Core
  - pip
  - python=3
  - jupyter
  - freetype=2.10.4
  # Lectures
  - statsmodels
  - networkx
  # Lab 1
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - ipywidgets
  # Lab 2
  - scikit-learn
  # Lab 3
  - pytest
  - pytest-benchmark
  - pip:
    - cobra
    - escher
    - gseapy
    - markupsafe==2.0.1
